import Head from 'next/head';
import {Fragment } from 'react';
import Header from '../comopnents/Header/Header';
import MainContent from '../comopnents/MainContent/MainContent';



export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContent />
    </Fragment>
  )
}
